development:
  adapter: MongoDB
  host: localhost
  database: testappdatabase

test: &TEST
  adapter: MongoDB
  host: localhost
  database: testappdatabase

production:
  adapter: MongoDB
  host: localhost
  database: testappdatabase
